/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hackbattle;

/**
 *
 * @author ankesh
 */
public class usercntrl extends javax.swing.JFrame {

    /**
     * Creates new form usercntrl
     */
    public usercntrl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LOGOUT = new javax.swing.JMenuItem();
        CHNGPWD = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CLEANREPORT = new javax.swing.JMenuItem();
        ITEMREPORT = new javax.swing.JMenuItem();
        CANTEEN = new javax.swing.JMenuItem();
        EVENT = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("HOME");

        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jMenu1.add(LOGOUT);

        CHNGPWD.setText("CHANGEPASSWORD");
        CHNGPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHNGPWDActionPerformed(evt);
            }
        });
        jMenu1.add(CHNGPWD);

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jMenu1.add(EXIT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("USERCNTROL ");

        CLEANREPORT.setText("CLEAN REPORT");
        CLEANREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEANREPORTActionPerformed(evt);
            }
        });
        jMenu2.add(CLEANREPORT);

        ITEMREPORT.setText("ITEM REPORT");
        ITEMREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMREPORTActionPerformed(evt);
            }
        });
        jMenu2.add(ITEMREPORT);

        CANTEEN.setText("CANTEEN ORDER");
        CANTEEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTEENActionPerformed(evt);
            }
        });
        jMenu2.add(CANTEEN);

        EVENT.setText("EVENT MSG");
        EVENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTActionPerformed(evt);
            }
        });
        jMenu2.add(EVENT);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("NOTICE BOARD");

        jMenuItem2.setText("EVENT LIST");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setText("FOUND ITEM");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ITEMREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMREPORTActionPerformed
        // TODO add your handling code here:
          itemreport f=new itemreport();
        this.add(f);
        f.show();
    }//GEN-LAST:event_ITEMREPORTActionPerformed

    private void CHNGPWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHNGPWDActionPerformed
  //fcpwd f=new fcpwd();
   //     this.add(f);
     //   f.show();        // TODO add your handling code here:
    }//GEN-LAST:event_CHNGPWDActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
  home a=new home();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void CLEANREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEANREPORTActionPerformed
        // TODO add your handling code here:
        clean f=new clean();
        this.add(f);
        f.show();
    }//GEN-LAST:event_CLEANREPORTActionPerformed

    private void CANTEENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTEENActionPerformed
       canteen f=new canteen();
        this.add(f);
        f.show();        // TODO add your handling code here:
    }//GEN-LAST:event_CANTEENActionPerformed

    private void EVENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTActionPerformed
        // TODO add your handling code here:
         event f=new event();
        this.add(f);
        f.show();
    }//GEN-LAST:event_EVENTActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         eventtbl t= new eventtbl();
        this.add(t);
        t.show();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
           fnditm t= new fnditm();
        this.add(t);
        t.show();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usercntrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usercntrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usercntrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usercntrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usercntrl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CANTEEN;
    private javax.swing.JMenuItem CHNGPWD;
    private javax.swing.JMenuItem CLEANREPORT;
    private javax.swing.JMenuItem EVENT;
    private javax.swing.JMenuItem EXIT;
    private javax.swing.JMenuItem ITEMREPORT;
    private javax.swing.JMenuItem LOGOUT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
