package java.project;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankesh
 */
public class fpass extends javax.swing.JFrame {

    /**
     * Creates new form fpass
     */
    public fpass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JLabel();
        fhint = new javax.swing.JLabel();
        fuser = new javax.swing.JTextField();
        fgethint = new javax.swing.JTextField();
        fnew = new javax.swing.JLabel();
        frenew = new javax.swing.JLabel();
        fsave = new javax.swing.JButton();
        hint = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        getpwd = new javax.swing.JPasswordField();
        renew = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fname.setText("Aadhar no");

        fuser.setBackground(new java.awt.Color(26, 252, 236));
        fuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuserActionPerformed(evt);
            }
        });

        fgethint.setBackground(new java.awt.Color(29, 247, 253));
        fgethint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgethintActionPerformed(evt);
            }
        });

        fnew.setText("New  pwd");

        frenew.setText("Re-enter pwd");

        fsave.setBackground(new java.awt.Color(245, 6, 52));
        fsave.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        fsave.setText("SAVE");
        fsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsaveActionPerformed(evt);
            }
        });

        hint.setText("Fav crop");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Help centre");

        getpwd.setBackground(new java.awt.Color(39, 241, 246));

        renew.setBackground(new java.awt.Color(15, 229, 240));

        jButton1.setBackground(new java.awt.Color(235, 7, 47));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fhint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fname)
                                        .addComponent(fnew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(frenew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(hint, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(renew, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fgethint)
                                        .addComponent(fuser)
                                        .addComponent(getpwd))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(fsave, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fgethint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhint)
                    .addComponent(hint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnew)
                    .addComponent(getpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frenew)
                    .addComponent(renew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fsave)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuserActionPerformed

    private void fgethintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgethintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fgethintActionPerformed

    private void fsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsaveActionPerformed
      String adhr= fuser.getText();
      String hnt= fgethint.getText();
      String npass=getpwd.getText();
      String conpass=renew.getText();
      if(adhr.length()==12)
      {
      try
        {
         Class.forName("com.mysql.jdbc.Driver");
         String str="jdbc:mysql://localhost/mandi";
         Connection x=DriverManager.getConnection(str,"root","12345");
         //System.out.println("ankesh");

           String query="select hint from farmer where adhar=?";

            PreparedStatement ps=x.prepareStatement(query);
            ps.setString(1, adhr);
            ResultSet rs=ps.executeQuery();
             if (rs.next()==false)
            {
             JOptionPane.showMessageDialog(this,"not valid id ");
             fpass f=new fpass();
             f.setVisible(true);
             this.dispose();
     
             }
             else
                {
                     String ht=rs.getString("hint");
                      if( ht.equals(hnt) && npass.equals(conpass))
                        {
                        
                                    /*try
                                    {
                                        //Class.forName("com.mysql.jdbc.Driver");
                                        String stri="jdbc:mysql://localhost/thunder";
                                            Connection r=DriverManager.getConnection(stri,"root","");
                                        //System.out.println("ankesh");
                                    */
                                        String qry="update farmer set pwd=? where adhar=?";

                                    try  {
                                        PreparedStatement pes=x.prepareStatement(qry);
                                        pes.setString(1, npass);
                                        pes.setString(2, adhr);
                                        pes.executeUpdate();
                                        JOptionPane.showMessageDialog(this,"passwordchange");
                                        flogin s=new flogin();
                                        s.setVisible(true);
                                        this.dispose();

                                    }
                                    catch(Exception es)
                                    {
                                        es.printStackTrace();
                                    }
                                
                        }
                      else
                      {
                          JOptionPane.showMessageDialog(this,"PWD OR HINT NOT MATCHED");
                          fpass f=new fpass();
                          f.setVisible(true);
                          this.dispose();
     
 
                      }
                }
        }  
        catch(Exception ex)
        {
            ex.printStackTrace();
        } 
      }
      else
      {
        JOptionPane.showMessageDialog(this,"INVALID AADHAR NO");
        JOptionPane.showMessageDialog(this,"MUST BE OF TWELVE CHARACTER");
        fpass f=new fpass();
        f.setVisible(true);
        this.dispose();
        
      }
      
    }//GEN-LAST:event_fsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        flogin f=new flogin();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fgethint;
    private javax.swing.JLabel fhint;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel fnew;
    private javax.swing.JLabel frenew;
    private javax.swing.JButton fsave;
    private javax.swing.JTextField fuser;
    private javax.swing.JPasswordField getpwd;
    private javax.swing.JLabel hint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField renew;
    // End of variables declaration//GEN-END:variables
}
