
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankesh
 */
public class chngpwd extends javax.swing.JInternalFrame {

    /**
     * Creates new form chngpwd
     */
    public chngpwd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usr = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        npwd = new javax.swing.JLabel();
        conpwd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        getusr = new javax.swing.JTextField();
        getpwd = new javax.swing.JTextField();
        getnpwd = new javax.swing.JTextField();
        getconpwd = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);

        usr.setText("username");

        pwd.setText("old password");

        npwd.setText("new password");

        conpwd.setText("confirm password");

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(npwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conpwd, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getpwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getusr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getnpwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getconpwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usr)
                    .addComponent(getusr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npwd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getnpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getconpwd))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String uname= getusr.getText();
      String oldpwd= getpwd.getText();
      String npass=getnpwd.getText();
      String conpass=getconpwd.getText();
      try
        {
         Class.forName("com.mysql.jdbc.Driver");
         String str="jdbc:mysql://localhost/thunder";
         Connection x=DriverManager.getConnection(str,"root","");
         //System.out.println("ankesh");

           String query="select pwd from user where uname=?";

            PreparedStatement ps=x.prepareStatement(query);
            ps.setString(1, uname);
            ResultSet rs=ps.executeQuery();
             if (rs.next()==false)
            {
             JOptionPane.showMessageDialog(this,"not valid id ");
             fpass f=new fpass();
             f.setVisible(true);
             this.dispose();
     
             }
             else
                {
                     String ht=rs.getString("pwd");
                     System.out.println(ht);
                     System.out.println(oldpwd);
                      if( ht.equals(oldpwd) && npass.equals(conpass))
                        {
                                        String qry="update user set pwd=? where uname=?";

                                    try  {
                                        PreparedStatement pes=x.prepareStatement(qry);
                                        pes.setString(1, npass);
                                        pes.setString(2, uname);
                                        pes.executeUpdate();
                                        JOptionPane.showMessageDialog(this,"passwordchange");
                                         this.dispose();

                                    }
                                    catch(Exception es)
                                    {
                                        es.printStackTrace();
                                    }
                                
                        }
                      else
                      {
                          JOptionPane.showMessageDialog(this,"PWD NOT MATCHED");
                          chngpwd f=new chngpwd();
                          f.setVisible(true);
                          this.dispose();
     
 
                      }
                }
        }  
        catch(Exception ex)
        {
            ex.printStackTrace();
        } 
 
      
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conpwd;
    private javax.swing.JTextField getconpwd;
    private javax.swing.JTextField getnpwd;
    private javax.swing.JTextField getpwd;
    private javax.swing.JTextField getusr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel npwd;
    private javax.swing.JLabel pwd;
    private javax.swing.JLabel usr;
    // End of variables declaration//GEN-END:variables
}
