
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankesh
 */
public class inbid extends javax.swing.JInternalFrame {
 
    /**
     * Creates new form inbid
     */ ArrayList cropdata=new ArrayList();
     String sd;
     String name;
     String md;
     String s;
     String acc;
    public inbid(String name,String acc) {
        initComponents();
        this.name=name;
        this.acc=acc;
        bidd.setVisible(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    void GetMuser()
    {
    try
 {
 Class.forName("com.mysql.jdbc.Driver");
 String str="jdbc:mysql://localhost/mandi";
 Connection x=DriverManager.getConnection(str,"root","12345");

String query="select user from merchant where adhar=? ";

PreparedStatement ps=x.prepareStatement(query);
ps.setString(1,md);
ResultSet rs=ps.executeQuery();
 while (rs.next())
 {
      
     s=rs.getString("user");
    // gtcrop.addItem(rs.getString("Cropname"));
 }
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
   }
         void showData() {
try
{
        // Vector heading=new Vector();
        Vector heading = new Vector();
      heading.add("MID");
      heading.add("Amount");
      heading.add("Status");
  
      
         sd=id.getText();

        Class.forName("com.mysql.jdbc.Driver");
        String str = "jdbc:mysql://localhost/mandi";
        Connection x = DriverManager.getConnection(str, "root", "12345");
        String query = "select  M_ID,Amount,Status from Status where sid=? ";
        PreparedStatement ps = x.prepareStatement(query);
        ps.setString(1, sd);
        ResultSet rs=ps.executeQuery();
         Vector data = new Vector();
        while(rs.next())
        {
             Vector row = new Vector();
             //row.add(rs.getString("sid"));
            row.add(rs.getString("M_ID"));
            row.add(rs.getString("Amount"));
             row.add(rs.getString("Status"));
               data.add(row);
        }
       
        DefaultTableModel d=new DefaultTableModel(data,heading);
       bidtable.setModel(d);
       
        
}
catch(Exception ex)
{
 JOptionPane.showMessageDialog(this, ex.getMessage());
}
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bidtable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        bidd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ACCEPT = new javax.swing.JButton();
        MID = new javax.swing.JTextField();
        amnt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stat = new javax.swing.JTextField();
        reject = new javax.swing.JButton();
        id = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        bidtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "M_ ID", "AMOUNT", "STATUS"
            }
        ));
        bidtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bidtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bidtable);
        if (bidtable.getColumnModel().getColumnCount() > 0) {
            bidtable.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        jLabel5.setText("STOCK ID");

        show.setBackground(new java.awt.Color(236, 13, 63));
        show.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        jLabel2.setText("M_ID");

        ACCEPT.setBackground(new java.awt.Color(240, 7, 53));
        ACCEPT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ACCEPT.setText("ACCEPT");
        ACCEPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCEPTActionPerformed(evt);
            }
        });

        MID.setBackground(new java.awt.Color(36, 226, 216));

        amnt.setBackground(new java.awt.Color(33, 214, 234));

        jLabel6.setText("Amount");

        jLabel8.setText("Status");

        stat.setBackground(new java.awt.Color(31, 208, 250));

        reject.setBackground(new java.awt.Color(248, 3, 41));
        reject.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        reject.setText("REJECT");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout biddLayout = new javax.swing.GroupLayout(bidd);
        bidd.setLayout(biddLayout);
        biddLayout.setHorizontalGroup(
            biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biddLayout.createSequentialGroup()
                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biddLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(biddLayout.createSequentialGroup()
                                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(amnt, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(MID)
                                    .addComponent(stat, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(biddLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(biddLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ACCEPT, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(reject, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        biddLayout.setVerticalGroup(
            biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biddLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(biddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACCEPT)
                    .addComponent(reject))
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        id.setBackground(new java.awt.Color(18, 250, 244));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(show))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bidd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bidd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        showData();
      
    }//GEN-LAST:event_showActionPerformed

    private void bidtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bidtableMouseClicked
 int index= bidtable.getSelectedRow();
       
        TableModel tm=bidtable.getModel();
       String mid=(String) tm.getValueAt(index, 0);
       String amt=(String)tm.getValueAt(index, 1);
        String stts=(String)tm.getValueAt(index, 2);
        
        stat.setText(stts);
        MID.setText(mid);
        amnt.setText(amt);
        bidd.setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_bidtableMouseClicked

    private void ACCEPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCEPTActionPerformed
        // TODO add your handling code here:
         md=MID.getText();
         
          GetMuser();
            try
        {
         Class.forName("com.mysql.jdbc.Driver");
        String str = "jdbc:mysql://localhost/mandi";
        Connection x = DriverManager.getConnection(str, "root", "12345");
        String query = "update Status set Status=? where M_ID!=? and sid=?";
        PreparedStatement ps = x.prepareStatement(query);
        ps.setString(1, "REJECTED");
        ps.setString(2, md);
        ps.setString(3,sd);
        int ch=ps.executeUpdate();
       // JOptionPane.showMessageDialog(this,ch);
 if (ch>=0)
 {
     String q = "update Status set Status=? where M_ID=? and sid=?";
        PreparedStatement p = x.prepareStatement(q);
        p.setString(1, "Accepted");
        p.setString(2, md);
        p.setString(3,sd);
        p.executeUpdate();
JOptionPane.showMessageDialog(this,"MODIFY SUCCESFULLY");
JOptionPane.showMessageDialog(this,"Email sent11"+s);
showData();
String msg=" PAY  CASH ON DELIVERY TO ACC NO:-"+acc+ " AND ORDER WILL BE DELIVERED WITHIN 7 DAYS ";
mailtest.sendEmail(s,"BID ACCEPTED", msg,name);
JOptionPane.showMessageDialog(this,"Email sent");
this.dispose();
 }
       
        
}
catch(Exception ex)
{
 JOptionPane.showMessageDialog(this, ex.getMessage());
}
   
        
        
    }//GEN-LAST:event_ACCEPTActionPerformed

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        // TODO add your handling code here:
        String mid=MID.getText();
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
        String str = "jdbc:mysql://localhost/mandi";
        Connection x = DriverManager.getConnection(str, "root", "12345");
        String query = "update Status set Status=? where M_ID=? and sid=?";
        PreparedStatement ps = x.prepareStatement(query);
        ps.setString(1, "REJECTED");
        ps.setString(2, mid);
        ps.setString(3,sd);
        int ch=ps.executeUpdate();
 if (ch==1)
 {
JOptionPane.showMessageDialog(this,"BID REJECTED");
showData();
this.dispose();
 }
       
        
}
catch(Exception ex)
{
 JOptionPane.showMessageDialog(this, ex.getMessage());
}
   
        
    }//GEN-LAST:event_rejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACCEPT;
    private javax.swing.JTextField MID;
    private javax.swing.JTextField amnt;
    private javax.swing.JPanel bidd;
    private javax.swing.JTable bidtable;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reject;
    private javax.swing.JButton show;
    private javax.swing.JTextField stat;
    // End of variables declaration//GEN-END:variables
}
