
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankesh
 */
public class salestock extends javax.swing.JInternalFrame {

    /**
     * Creates new form salestock
     */
    
    ArrayList cropdata=new ArrayList();
    String adhaar;
    String doe,sd;
    int amount;
    public salestock(String adhaar) {
        
        initComponents();
        this.adhaar=adhaar;
        bid.setVisible(false);
        fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      void fillcombo()
    {
       
    try
 {
 Class.forName("com.mysql.jdbc.Driver");
 String str="jdbc:mysql://localhost/mandi";
 Connection x=DriverManager.getConnection(str,"root","12345");

String query="select Cropid,Cropname from cat";

PreparedStatement ps=x.prepareStatement(query);
ResultSet rs=ps.executeQuery();
 while (rs.next())
 {
     String s[]=new String[2];
     s[0]=rs.getString("Cropid");
     s[1]=rs.getString("Cropname");
     
    cropdata.add(s);
     getcrop.addItem(rs.getString("Cropname"));
 }
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
   }
         void showData() {
try
{
        // Vector heading=new Vector();
        Vector heading = new Vector();
      heading.add("Adharno");
      heading.add("Farmer name");
      heading.add("Price(Rs)");
      heading.add("Quantity(KG)");
      heading.add("DOE");
      heading.add("SID");
      
        String cropname=(String)getcrop.getSelectedItem();
         
        Class.forName("com.mysql.jdbc.Driver");
        String str = "jdbc:mysql://localhost/mandi";
        Connection x = DriverManager.getConnection(str, "root", "12345");
        String query = "select sid,adharno,user,Quantity,rate,doe from Stck,farm where farm.adhar=Stck.adharno and Stck.cropname=?";
        PreparedStatement ps = x.prepareStatement(query);
        ps.setString(1, cropname);
        ResultSet rs=ps.executeQuery();
         Vector data = new Vector();
        while(rs.next())
        {
             Vector row = new Vector();
             row.add(rs.getString("adharno"));
            row.add(rs.getString("user"));
             row.add(rs.getString("rate"));
             row.add(rs.getString("Quantity"));
             row.add(rs.getString("doe"));
              row.add(rs.getString("sid"));
               data.add(row);
        }
        
        DefaultTableModel d=new DefaultTableModel(data,heading);
       saletable.setModel(d);
        
}
catch(Exception ex)
{
ex.printStackTrace();
}
  }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getcrop = new javax.swing.JComboBox<>();
        show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        saletable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bid = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        adhr = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CROP FOR SALE");

        getcrop.setBackground(new java.awt.Color(33, 236, 234));
        getcrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcropActionPerformed(evt);
            }
        });

        show.setBackground(new java.awt.Color(238, 7, 70));
        show.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        saletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ADHAR NO.", "FARMER   NAME", "PRICE", "QUANTITY(kg)", "DOE", "SID"
            }
        ));
        saletable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saletableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(saletable);
        if (saletable.getColumnModel().getColumnCount() > 0) {
            saletable.getColumnModel().getColumn(0).setPreferredWidth(50);
            saletable.getColumnModel().getColumn(2).setPreferredWidth(2);
            saletable.getColumnModel().getColumn(3).setPreferredWidth(20);
            saletable.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        jLabel1.setText("CROP NAME");

        jLabel2.setText("Adhar no");

        jLabel4.setText("Quantity(kg)");

        jLabel5.setText("amount");

        amt.setBackground(new java.awt.Color(14, 195, 229));

        adhr.setBackground(new java.awt.Color(28, 236, 247));

        qty.setBackground(new java.awt.Color(27, 217, 240));

        save.setBackground(new java.awt.Color(249, 8, 88));
        save.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bidLayout = new javax.swing.GroupLayout(bid);
        bid.setLayout(bidLayout);
        bidLayout.setHorizontalGroup(
            bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bidLayout.createSequentialGroup()
                .addGroup(bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bidLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bidLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(qty)
                    .addComponent(adhr)))
            .addGroup(bidLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bidLayout.setVerticalGroup(
            bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bidLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(bidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getcrop, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getcrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(bid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getcropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getcropActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_showActionPerformed

    private void saletableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saletableMouseClicked
        // TODO add your handling code here:
        try{
         int index= saletable.getSelectedRow();
       
        TableModel tm=saletable.getModel();
        String adhar=(String) tm.getValueAt(index, 0);
        String Qty=(String) tm.getValueAt(index, 3);
        doe=(String) tm.getValueAt(index, 4);
        sd=(String) tm.getValueAt(index,5 );
        String price=(String) tm.getValueAt(index,2 );
        adhr.setText(adhar);
        qty.setText(Qty);
        amount= (Integer.parseInt(Qty)* Integer.parseInt(price));
          String s=Integer.toString(amount);
          amt.setText(s);
        bid.setVisible(true);
        }
        catch(Exception ex)
        {
              JOptionPane.showMessageDialog(this, ex.getMessage());
              ex.printStackTrace();
        }
       
    }//GEN-LAST:event_saletableMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       
        int index=getcrop.getSelectedIndex();
        String x[]=(String [])cropdata.get(index);
        String cropid=x[0];
        String amnt=amt.getText();
        String status= "pending";
      try
    {                      
     Class.forName("com.mysql.jdbc.Driver");
     String str="jdbc:mysql://localhost/mandi";
     Connection y=DriverManager.getConnection(str,"root","12345");

     String query="insert into Status (cropid,M_ID,Sid ,Amount,doe,Status ) values(?,?,?,?,?,?) ";

     PreparedStatement ps=y.prepareStatement(query);
       ps.setString(1,cropid );
       ps.setString(2,adhaar); 
       ps.setString(3,sd); 
       ps.setString(4,amnt); 
       ps.setString(5,doe); 
       ps.setString(6,status); 

       ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"DATA SAVED");
       
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
       
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adhr;
    private javax.swing.JTextField amt;
    private javax.swing.JPanel bid;
    private javax.swing.JComboBox<String> getcrop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField qty;
    private javax.swing.JTable saletable;
    private javax.swing.JButton save;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
